<<<<<<< HEAD
[build]
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "20" }
=======
  base = "project"
  publish = "project/dist"
>>>>>>> 2320ba7ca75b9f0f27f8a306b4221a65ca2d6563

